<template>
  <q-page>
    <ReusableTable
      :rows="animals"
      :columns="animalColumns"
      separator="vertical"
      title="Veterinary Schedule"
      v-model="search"
      :rows-per-page-options="[10]"
      :visible-columns="[
        'id',
        'name',
        'type',
        'breed',
        'age',
        'size',
        'gender',
        'color',
        'behavior',
        'adoptedStatus',
      ]"
    >
      <template #cell-name="{ row }">
        <q-avatar size="30px" class="q-mr-md">
          <img :src="row.image || defaultImage" />
        </q-avatar>
        {{ row.name }}
      </template>
    </ReusableTable>
  </q-page>
</template>

<script>
import ReusableTable from 'src/components/ReusableTable.vue'
import { ref } from 'vue'
export default {
  components: { ReusableTable },
  setup() {
    const search = ref(null)
    return {
      search,
      animalColumns: [
        { name: 'id', label: 'ID', field: 'id', align: 'center' },
        { name: 'name', label: 'Name', field: 'name', sortable: true, align: 'left' },
        { name: 'type', label: 'Type', field: 'type', sortable: true, align: 'center' },
        { name: 'breed', label: 'Breed', field: 'breed', sortable: true, align: 'center' },
        { name: 'age', label: 'Age', field: 'age', sortable: true, align: 'center' },
        { name: 'size', label: 'Size', field: 'size', sortable: true, align: 'center' },
        { name: 'gender', label: 'Gender', field: 'gender', sortable: true, align: 'center' },
        { name: 'color', label: 'Color', field: 'color', align: 'center' },
        { name: 'goodWith', label: 'Good With', field: 'goodWith', align: 'center' },
        { name: 'behavior', label: 'Care & Behavior', field: 'behavior', align: 'center' },
        { name: 'healthStatus', label: 'Health Status', field: 'healthStatus', align: 'center' },
        { name: 'adoptedStatus', label: 'Adopted Status', field: 'adoptedStatus', align: 'center' },
      ],
      animals: [
        {
          id: 1,
          name: 'Bella',
          type: 'Dog',
          breed: 'Labrador Retriever',
          age: '3 years',
          size: 'Large',
          gender: 'Female',
          color: 'Yellow',
          goodWith: 'Kids, Dogs',
          behavior: 'Friendly, Playful',
          healthStatus: 'Healthy',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 2,
          name: 'Max',
          type: 'Dog',
          breed: 'German Shepherd',
          age: '5 years',
          size: 'Large',
          gender: 'Male',
          color: 'Black and Tan',
          goodWith: 'Adults, Dogs',
          behavior: 'Loyal, Protective',
          healthStatus: 'Needs Medication',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 3,
          name: 'Luna',
          type: 'Cat',
          breed: 'Siamese',
          age: '2 years',
          size: 'Medium',
          gender: 'Female',
          color: 'Cream and Brown',
          goodWith: 'Kids, Cats',
          behavior: 'Affectionate, Vocal',
          healthStatus: 'Healthy',
          adoptedStatus: 'Adopted',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 4,
          name: 'Charlie',
          type: 'Dog',
          breed: 'Beagle',
          age: '4 years',
          size: 'Medium',
          gender: 'Male',
          color: 'Tri-color',
          goodWith: 'Kids, Cats',
          behavior: 'Energetic, Curious',
          healthStatus: 'Recovering from Surgery',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 5,
          name: 'Daisy',
          type: 'Rabbit',
          breed: 'Holland Lop',
          age: '1 year',
          size: 'Small',
          gender: 'Female',
          color: 'White and Brown',
          goodWith: 'Kids',
          behavior: 'Gentle, Cuddly',
          healthStatus: 'Healthy',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 6,
          name: 'Rocky',
          type: 'Dog',
          breed: 'Pit Bull Terrier',
          age: '3 years',
          size: 'Medium',
          gender: 'Male',
          color: 'Gray',
          goodWith: 'Adults, Experienced Owners',
          behavior: 'Loyal, High Energy',
          healthStatus: 'Needs Training',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 7,
          name: 'Oliver',
          type: 'Cat',
          breed: 'Maine Coon',
          age: '6 years',
          size: 'Large',
          gender: 'Male',
          color: 'Orange Tabby',
          goodWith: 'Kids, Dogs',
          behavior: 'Independent, Loving',
          healthStatus: 'Healthy',
          adoptedStatus: 'Adopted',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 8,
          name: 'Milo',
          type: 'Dog',
          breed: 'Shih Tzu',
          age: '4 years',
          size: 'Small',
          gender: 'Male',
          color: 'White and Brown',
          goodWith: 'Kids, Elderly',
          behavior: 'Calm, Affectionate',
          healthStatus: 'Healthy',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 9,
          name: 'Chloe',
          type: 'Cat',
          breed: 'Persian',
          age: '3 years',
          size: 'Medium',
          gender: 'Female',
          color: 'Gray',
          goodWith: 'Quiet Homes, Adults',
          behavior: 'Quiet, Gentle',
          healthStatus: 'Needs Grooming',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 10,
          name: 'Buddy',
          type: 'Dog',
          breed: 'Golden Retriever',
          age: '7 years',
          size: 'Large',
          gender: 'Male',
          color: 'Golden',
          goodWith: 'Kids, Dogs, Cats',
          behavior: 'Friendly, Obedient',
          healthStatus: 'Senior Dog, Needs Supplements',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 11,
          name: 'Coco',
          type: 'Parrot',
          breed: 'African Grey',
          age: '12 years',
          size: 'Small',
          gender: 'Male',
          color: 'Grey with Red Tail',
          goodWith: 'Adults, Calm Homes',
          behavior: 'Intelligent, Talkative',
          healthStatus: 'Needs Special Diet',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
        {
          id: 12,
          name: 'Snowball',
          type: 'Guinea Pig',
          breed: 'American',
          age: '2 years',
          size: 'Small',
          gender: 'Female',
          color: 'White',
          goodWith: 'Kids, Calm Homes',
          behavior: 'Shy, Gentle',
          healthStatus: 'Healthy',
          adoptedStatus: 'Available',
          image: 'https://cdn.quasar.dev/img/cat.jpg',
        },
      ],
    }
  },
}
</script>
